import pytest
from users.tools import *
import requests
from users.sign import create_sign
from json import loads
import time
from users.user import User
from users import merchant
import pprint

class TestPaywayList:
    """ PaywayLis """

    def test_0(self, start_session):
        """ Warm. """
        global admin, user1, user2
        admin, user1, user2 = start_session
        admin.set_currency(is_crypto=False, admin_min=bl(0.01), admin_max='3000000000000')
        admin.set_currency(is_crypto=True, admin_min=bl(0.000001), admin_max='3000000000')

    def test_PaywayList_1(self):
        """ Payway List. """
        admin.set_pwmerchactive(merch_id=user1.merchant1.id, payway_id=admin.payway['payeer']['id'], is_active=True)
        user1.merchant1.payway_list()
        assert user1.merchant1.resp_payway_list['result'] == {'btc': {'currencies': [{'fee': {},
                                                  'is_crypto': True,
                                                  'is_out': True,
                                                  'name': None,
                                                  'precision': 8,
                                                  'tech_max': '101',
                                                  'tech_min': '1'},
                                                 {'fee': {'add': '0.0003',
                                                          'max': '0',
                                                          'method': 'ceil',
                                                          'min': '0',
                                                          'mult': '0.05'},
                                                  'is_crypto': True,
                                                  'is_out': False,
                                                  'name': None,
                                                  'precision': 8,
                                                  'tech_max': '3000',
                                                  'tech_min': '10'}],
                                  'is_active': True,
                                  'is_public': True,
                                  'type': 'crypto'},
                          'cash_kiev': {'currencies': [],
                                        'is_active': True,
                                        'is_public': True,
                                        'type': 'sci'},
                          'eth': {'currencies': [{'fee': {'add': '0',
                                                          'max': '0',
                                                          'method': 'ceil',
                                                          'min': '0',
                                                          'mult': '0'},
                                                  'is_crypto': True,
                                                  'is_out': False,
                                                  'name': None,
                                                  'precision': 8,
                                                  'tech_max': '3',
                                                  'tech_min': '0.000001'}],
                                  'is_active': True,
                                  'is_public': True,
                                  'type': 'crypto'},
                          'exmo': {'currencies': [{'fee': {},
                                                   'is_crypto': False,
                                                   'is_out': True,
                                                   'name': None,
                                                   'precision': 2,
                                                   'tech_max': '2',
                                                   'tech_min': '0.01'},
                                                  {'fee': {'add': '1',
                                                           'max': '0',
                                                           'method': 'ceil',
                                                           'min': '0',
                                                           'mult': '0.05'},
                                                   'is_crypto': False,
                                                   'is_out': False,
                                                   'name': None,
                                                   'precision': 2,
                                                   'tech_max': '2',
                                                   'tech_min': '0.01'},
                                                  {'fee': {'add': '0',
                                                           'max': '0',
                                                           'method': 'ceil',
                                                           'min': '0',
                                                           'mult': '0'},
                                                   'is_crypto': False,
                                                   'is_out': True,
                                                   'name': None,
                                                   'precision': 2,
                                                   'tech_max': '15.48',
                                                   'tech_min': '0.01'},
                                                  {'fee': {'add': '0',
                                                           'max': '0',
                                                           'method': 'ceil',
                                                           'min': '0',
                                                           'mult': '0'},
                                                   'is_crypto': False,
                                                   'is_out': False,
                                                   'name': None,
                                                   'precision': 2,
                                                   'tech_max': '3000',
                                                   'tech_min': '0.01'}],
                                   'is_active': True,
                                   'is_public': True,
                                   'type': 'cheque'},
                          'kuna': {'currencies': [{'fee': {'add': '0',
                                                           'max': '0',
                                                           'method': 'ceil',
                                                           'min': '0',
                                                           'mult': '0'},
                                                   'is_crypto': False,
                                                   'is_out': True,
                                                   'name': None,
                                                   'precision': 2,
                                                   'tech_max': '100',
                                                   'tech_min': '1'},
                                                  {'fee': {'add': '0.33',
                                                           'max': '0',
                                                           'method': 'ceil',
                                                           'min': '0',
                                                           'mult': '0'},
                                                   'is_crypto': False,
                                                   'is_out': False,
                                                   'name': None,
                                                   'precision': 2,
                                                   'tech_max': '3000',
                                                   'tech_min': '0.01'}],
                                   'is_active': True,
                                   'is_public': True,
                                   'type': 'cheque'},
                          'ltc': {'currencies': [{'fee': {},
                                                  'is_crypto': True,
                                                  'is_out': True,
                                                  'name': None,
                                                  'precision': 8,
                                                  'tech_max': '0.87627',
                                                  'tech_min': '0.002'},
                                                 {'fee': {'add': '0.001',
                                                          'max': '0',
                                                          'method': 'ceil',
                                                          'min': '0',
                                                          'mult': '0'},
                                                  'is_crypto': True,
                                                  'is_out': False,
                                                  'name': None,
                                                  'precision': 8,
                                                  'tech_max': '3',
                                                  'tech_min': '0.002'}],
                                  'is_active': True,
                                  'is_public': True,
                                  'type': 'crypto'},
                          'payeer': {'currencies': [{'fee': {'add': '0',
                                                             'max': '0',
                                                             'method': 'ceil',
                                                             'min': '0',
                                                             'mult': '0'},
                                                     'is_crypto': False,
                                                     'is_out': False,
                                                     'name': None,
                                                     'precision': 2,
                                                     'tech_max': '3000',
                                                     'tech_min': '0.01'},
                                                    {'fee': {},
                                                     'is_crypto': False,
                                                     'is_out': True,
                                                     'name': None,
                                                     'precision': 2,
                                                     'tech_max': '101',
                                                     'tech_min': '1'},
                                                    {'fee': {'add': '0',
                                                             'max': '0',
                                                             'method': 'ceil',
                                                             'min': '0',
                                                             'mult': '0'},
                                                     'is_crypto': False,
                                                     'is_out': False,
                                                     'name': None,
                                                     'precision': 2,
                                                     'tech_max': '3000',
                                                     'tech_min': '10'}],
                                     'is_active': True,
                                     'is_public': True,
                                     'type': 'sci'},
                          'paymer': {'currencies': [{'fee': {'add': '0',
                                                             'max': '0',
                                                             'method': 'ceil',
                                                             'min': '0',
                                                             'mult': '0'},
                                                     'is_crypto': False,
                                                     'is_out': False,
                                                     'name': None,
                                                     'precision': 2,
                                                     'tech_max': '3000',
                                                     'tech_min': '0.01'},
                                                    {'fee': {'add': '0',
                                                             'max': '0',
                                                             'method': 'ceil',
                                                             'min': '0',
                                                             'mult': '0'},
                                                     'is_crypto': False,
                                                     'is_out': False,
                                                     'name': None,
                                                     'precision': 2,
                                                     'tech_max': '3000',
                                                     'tech_min': '0.01'},
                                                    {'fee': {'add': '0',
                                                             'max': '0',
                                                             'method': 'ceil',
                                                             'min': '0',
                                                             'mult': '0'},
                                                     'is_crypto': False,
                                                     'is_out': True,
                                                     'name': None,
                                                     'precision': 2,
                                                     'tech_max': '3000',
                                                     'tech_min': '0.01'}],
                                     'is_active': True,
                                     'is_public': True,
                                     'type': 'cheque'},
                          'perfect': {'currencies': [{'fee': {},
                                                      'is_crypto': False,
                                                      'is_out': True,
                                                      'name': None,
                                                      'precision': 2,
                                                      'tech_max': '2.24',
                                                      'tech_min': '0.01'},
                                                     {'fee': {'add': '2',
                                                              'max': '0',
                                                              'method': 'ceil',
                                                              'min': '0',
                                                              'mult': '0.05'},
                                                      'is_crypto': False,
                                                      'is_out': False,
                                                      'name': None,
                                                      'precision': 2,
                                                      'tech_max': '3000',
                                                      'tech_min': '0.01'}],
                                      'is_active': True,
                                      'is_public': True,
                                      'type': 'sci'},
                          'privat24': {'currencies': [{'fee': {'add': '0',
                                                               'max': '0',
                                                               'method': 'ceil',
                                                               'min': '0',
                                                               'mult': '0'},
                                                       'is_crypto': False,
                                                       'is_out': False,
                                                       'name': None,
                                                       'precision': 2,
                                                       'tech_max': '3000',
                                                       'tech_min': '10'},
                                                      {'fee': {},
                                                       'is_crypto': False,
                                                       'is_out': True,
                                                       'name': None,
                                                       'precision': 2,
                                                       'tech_max': '93.97',
                                                       'tech_min': '1'}],
                                       'is_active': True,
                                       'is_public': True,
                                       'type': 'sci'},
                          'qiwi': {'currencies': [{'fee': {'add': '0',
                                                           'max': '0',
                                                           'method': 'ceil',
                                                           'min': '0',
                                                           'mult': '0'},
                                                   'is_crypto': False,
                                                   'is_out': False,
                                                   'name': None,
                                                   'precision': 2,
                                                   'tech_max': '3000',
                                                   'tech_min': '1'}],
                                   'is_active': True,
                                   'is_public': True,
                                   'type': 'sci'},
                          'visamc': {'currencies': [{'fee': {'add': '0',
                                                             'max': '0',
                                                             'method': 'ceil',
                                                             'min': '0',
                                                             'mult': '0'},
                                                     'is_crypto': False,
                                                     'is_out': False,
                                                     'name': None,
                                                     'precision': 2,
                                                     'tech_max': '3000',
                                                     'tech_min': '10'},
                                                    {'fee': {'add': '0',
                                                             'max': '0',
                                                             'method': 'ceil',
                                                             'min': '0',
                                                             'mult': '0'},
                                                     'is_crypto': False,
                                                     'is_out': True,
                                                     'name': None,
                                                     'precision': 2,
                                                     'tech_max': '101',
                                                     'tech_min': '1'},
                                                    {'fee': {'add': '0',
                                                             'max': '0',
                                                             'method': 'ceil',
                                                             'min': '0',
                                                             'mult': '0'},
                                                     'is_crypto': False,
                                                     'is_out': True,
                                                     'name': None,
                                                     'precision': 2,
                                                     'tech_max': '93.97',
                                                     'tech_min': '1'},
                                                    {'fee': {'add': '2',
                                                             'max': '0',
                                                             'method': 'ceil',
                                                             'min': '0',
                                                             'mult': '0.01'},
                                                     'is_crypto': False,
                                                     'is_out': False,
                                                     'name': None,
                                                     'precision': 2,
                                                     'tech_max': '3000',
                                                     'tech_min': '10'}],
                                     'is_active': True,
                                     'is_public': True,
                                     'type': 'sci'},
                          'webmoney': {'currencies': [],
                                       'is_active': True,
                                       'is_public': True,
                                       'type': 'sci'}}


